### PR TITLE
Enhanced facet filter margins

### PR DESCRIPTION
**Pull request by verheyenkoen**
Enhanced facet filter margins with gap so there's no need to determine the last item and set margin dynamically.
CLOSES #1393

### CODE REVIEW

**Review by nicolasfranck — APPROVED** [review]

**Comment by mietcls** [comment]
I gave feedback here @verheyenkoen: https://github.com/ugent-library/biblio-ugent-prototype/pull/17

**Comment by verheyenkoen** [comment]
@mietcls Unless I'm missing something, the only difference I see between your change and what is in this PR is you removed a nested `<div>` which I tried at first but it doesn't work well (or needs to be fixed in some other way).

```html
<div class="dropdown-menu__body border-bottom d-flex flex-column gap-4">
    ...
</div>
```
instead of:
```html
<div class="dropdown-menu__body border-bottom">
    <div class="d-flex flex-column gap-4">
        ...
    </div>
</div>
```
This is what you get when you nest both divs (probably only a problem when facet texts are wrapped):
image

**Comment by nics** [comment]
@mietcls @koen what's the status of this?

**Comment by verheyenkoen** [comment]
Awaiting feedback from @mietcls

**Comment by mietcls** [comment]
Correct @verheyenkoen – apologies. There's a non-urgent minor adjustment for the titles as well so they align with the select button, but I can add that optimisation later.

**Pull request merged**
