### PR TITLE
Added dynamic breadcrumbs #1337

### LINKED ISSUE #1337: Make breadcrumb path available in topbar for easy navigation
# Enhancement
Make breadcrumb path available in topbar for easy navigation.
This is preparation to reach multiple interfaces.

Screenshot 2023-12-05 at 10 00 43

https://biblio-backend-ugent-prototype-git-bootstr-307d84-ugent-library.vercel.app/biblio/researcher/publications/detail/full-view.html

## Expected behaviour
For each step down the line – I see a breadcrumb appear. When I want to go back one step, I can click the breadcrumb. 

Current steps:
- Ghent University Library
  - Biblio
    - Dashboard (researcher)
    - Dashboard (librarian)
    - Publications
      - Publication detail
      - New publication (we do not drill down further as we will make a different import flow later)
        - Import via Web of Science
        - Import via identifier
        - Add manually
        - Import via BibTex
    - Datasets
      - Dataset detail
      - New dataset (we do not drill down further as we will make a different import flow later)
        - Import via identifier
        - Add manually
    - Batch import

Out of scope: import flow

### PR DESCRIPTION
**Pull request by verheyenkoen**
Added breadcrumb functionality via PageLayout arguments, eg:

```go
templ Show(c *ctx.Ctx, p *models.Publication, redirectURL string) {
	@views.PageLayout(c, views.PageLayoutArgs{
		Title: c.Loc.Get("publication.page.show.title"),
		Breadcrumbs: []views.Breadcrumb{
			{LabelID: "publications", URL: c.PathTo("publications")}, // Breadcrumb with link
			{LabelID: "publication"}, // Breadcrumb without link
		},
	}) {
            // ...
```

Each breadcrumb should be translated in a .po file with the context "breadcrumbs" using this format:

```pot
msgctxt "breadcrumbs"
msgid "dashboard"
msgstr "Dashboard"
```

FIXES #1337

### CODE REVIEW

**Review by mietcls — APPROVED** [review]
Behaves as expected visually. Would work well for next steps with new import flow and detail views. Would not go into detail with the current import flow and breadcrumbs as it has to be replaced anyways.

**Review by nicolasfranck — COMMENTED** [review]
When you enter record detail view, you'll see a difference between:

* the link "back to overview" that links to /publications with search filter and filters
* the link "publications" in the breadcrumb that links to /publications but without search filter and filters.

Same goes for the dataset detail page

Expected?

**Comment by nics** [comment]
@verheyenkoen as discussed, refactor this to some simple view helpers (~ set page title)

**Review by nics — CHANGES_REQUESTED** [review]
@verheyenkoen as discussed, refactor this to some simple view helpers (~ set page title)

**Comment by mietcls** [comment]
> When you enter record detail view, you'll see a difference between:
> 
> * the link "back to overview" that links to /publications with search filter and filters
> * the link "publications" in the breadcrumb that links to /publications but without search filter and filters.
> 
> Same goes for the dataset detail page
> 
> Expected?

@nicolasfranck this is going to change when the import flow is completely redesigned. Intended for now.

**Comment by verheyenkoen** [comment]
> @verheyenkoen as discussed, refactor this to some simple view helpers (~ set page title)

Fixed in c7ea5ce7a9b7656b1679dbb45424f7caa9cd8ac5

**Review by nics — APPROVED** [review]

**Pull request merged**
