### PR TITLE
Add missing fields for misc

### PR DESCRIPTION
**Pull request by mietcls**
Fixes https://github.com/ugent-library/biblio-backoffice/issues/1179

### CODE REVIEW

**Comment by nics** [comment]
@mietcls we also need corresponding form fields

**Comment by mietcls** [comment]
Whoops, missed that – added!

**Comment by mietcls** [comment]
@nicolasfranck can you explain me what I did wrong and what was expected? Thanks!

**Comment by nicolasfranck** [comment]
@mietcls I'll make some changes

**Review by nicolasfranck — APPROVED** [review]

**Review by nicolasfranck — APPROVED** [review]

**Review by nicolasfranck — APPROVED** [review]

**Comment by mietcls** [comment]
> @mietcls already made changes here: [99b371e](https://github.com/ugent-library/biblio-backoffice/commit/99b371e192a91f2c0a82143dbcd284fa226d2739)

I see. What are the steps to keep in mind when adding/removing a field from a type of publication?

**Pull request merged**
