### PR TITLE
fix issue 1246

### LINKED ISSUE #1246: Close button on toast does not work
# Bug description
The close button on a toast should dismiss the toast but that doesn't seem to happen.

# Steps to Reproduce

Happens on multiple toast instances:

1. After deleting a publication
1. After publishing a publication
1. After withdrawing a publication
1. After republishing a publication
1. After locking a publication
1. After unlocking a publication

### Likelihood

1. Frequent (always)

### Consequences

3. Marginal

# Expected behavior

The toast should disappear immediately.

# System information

## Desktop
 - OS: MacOS
 - Browser: Chrome

# Additional context

Maybe the toast should also close upon hitting the `ESCAPE` key.

### PR DESCRIPTION
**Pull request by nicolasfranck**
fixes #1246 

Apparently in the past the close button in the toast had a class named `toast-dismiss`,
but logic has been removed since 54876fe6f71fd651d3ae345e56f08b80f62716e4.

I changed the query selector in toast.js.

@mietcls 

Note: do I have to rebuild the static assets too?

### CODE REVIEW

**Comment by nics** [comment]
@nicolasfranck yes always include the new assets

**Comment by nicolasfranck** [comment]
There you go @nics

**Review by nics — APPROVED** [review]

**Comment by verheyenkoen** [comment]
Remember this merge includes the tests for this issue but they will fail if bibliodev is not redeployed.

**Comment by nics** [comment]
@verheyenkoen will deploy later today

**Pull request merged**
