### PR TITLE
fix issue 956

### LINKED ISSUE #956: {filters} Make contrast between active, inactive, enabled an disabled filters more clear
# Story

Part of #954 

Right now, it is hard to easily scan which filters are in use without having to read everything and squint your eyes. This is not accessible for people with visible impairments.

Scherm­afbeelding 2023-01-06 om 15 33 16

## Proposed solution
- Make filters **with** selected options bright blue (even if they have 0 results)
- Make filters _without_ selected options, **with** available options light blue
- Make filters _without_ selected options, _without_ available options light gray

Scherm­afbeelding 2023-01-06 om 15 46 52

### Context for filters _without_ selected options, _without_ available options light gray:
Sometimes we can combine filters in a way that causes other filters become "unfruitful", and they will look like this:
Scherm­afbeelding 2023-01-19 om 11 57 37

We want to make sure the user knows these are not "fruitful".
We will make exceptions for
- "created since" and "updated since" – as we cannot make the distinction here.
- filters that "_became unfruitful_" during selection and return filter options with 0 – they remain bright blue

### Success criteria
- [ ] Filters that _do_ have one or more filter options available
and _does not have_ any filter options are selected
**appear as "default", light blue**
- [ ] Filters that _do_ have one or more filter options available
and _does have_ filter options selected
**appear as "primary", bright blue**
- [ ] Filters that _do not_ have any fruitful filter options available (clicking options = 0 results)
and _does have_ one or more filter options selected
**appear as "primary", bright blue**
- [ ] Filters that _do not_ have any fruitful filter options available (clicking options = 0 results)
and _does not have_ any  one or more filter options selected
**appear as "secondary", light gray**
  - [ ] Exception for "created since" and "updated since" – as we cannot make the distinction of "fruitfulness" for these filters.

## Implementation suggestion
Find the badges layouts here: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-badges.html

### Default: non-active filter + filter options available 
`badge-default`
Scherm­afbeelding 2023-01-06 om 15 53 04
```
<div class="dropdown">
    <a class="badge badge-default mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

### Active filter
`badge-primary`
Scherm­afbeelding 2023-01-06 om 15 53 17
```
<div class="dropdown">
    <a class="badge badge-primary mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

### Non-active filter + no filter options available
`badge-secondary`
Scherm­afbeelding 2023-01-06 om 15 53 28
```
<div class="dropdown">
    <a class="badge badge-secondary mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

## More context

Decided not to block anyone from clicking a filter box when there are no filter options available to check. It would require more complex rules and unnecessary blocks.

### PR DESCRIPTION
**Pull request by nicolasfranck**
fixes #956

### CODE REVIEW

**Review by nics — COMMENTED** [review]
@nicolasfranck @mietcls can't this be solved with some css (`:has` and `+`)?

**Comment by mietcls** [comment]
That is indeed an option – I'd have to retrieve some information.

I've done a little experiment, but it seems that some information is not showing in the dom somehow which is why I can't use :has. Will look into it.

**Comment by nicolasfranck** [comment]
@nics @mietcls well especially for the greyed out filters you will have to need some "data" in the elements, and some counters that say "all of these elements have an attribute with value 0". Not sure if that's possible.

**Comment by nicolasfranck** [comment]
@mietcls @nics what's the status on this?

**Comment by nics** [comment]
@mietcls @nicolasfranck I'm implementing this with some css voodoo:

```scss
.badge-list {
    .dropdown:has(:checked) .badge-default {
        @extend .badge-primary;
    }
}
```

**Comment by nics** [comment]
replaced by 0f5d34c2979554f349bfd6310c86b0f28ceee10d

**Pull request closed without merging**
