### PR TITLE
provide better error messages when importing publications/datasets

### LINKED ISSUE #1138: Provide error: DOI not recognised by trusted service

### PR DESCRIPTION
**Pull request by nicolasfranck**
fixes #1138 #1135 #1136 #1137

So

* provides error for "bad connection"
* provides error for "not found" (if it can be determined)
* provides error for "invalid content"

TODO: I have put the text in translations.go, but .. that contains also html data. So feels a bit off.

### CODE REVIEW

**Comment by mietcls** [comment]
@nicolasfranck which parts do you mean? Do we need to rewrite information?

**Comment by nicolasfranck** [comment]
@mietcls not sure if that is possible.

What I mean: for each situation (bad connection, resource not found ..), a localized message (stored in the translation map) needs to be put in the "body" of the toaster.
In the past that body of the toaster was merely a sentence, with here and there simple tags like `<a>` or `<i>`. But now the body needs to have a whole html structure. That fills the translation map with data like `"<div style=\"display:none\">I do not want you to see this</div> are we good?"`, data you would expect in a template...

**Comment by nicolasfranck** [comment]
@mietcls yes it works, but putting a lot of html in a translation map makes it unreadable.

**Comment by mietcls** [comment]
@nicolasfranck yes that's true. There are plans to move this to a different format, where it becomes more manageable.

**Comment by nicolasfranck** [comment]
to delete or split up? @netsensei @nics

**Comment by netsensei** [comment]
@nicolasfranck @nics @mietcls I'm closing this. This an attempt to create error messages which were not useful enough for end users. See #1091  => needs to be turned into a discussion to hash out how we want to move this one forward.

**Pull request closed without merging**
